       // --- Word Data ---
        const wordData = [
          // --- Level 1 (সাধারণ ও ছোট শব্দ) ---
          { word: "কলম", parts: ["ক", "ল", "ম"], minLevel: 1 },
          { word: "বই", parts: ["ব", "ই"], minLevel: 1 },
          { word: "খাতা", parts: ["খা", "তা"], minLevel: 1 },
          { word: "জল", parts: ["জ", "ল"], minLevel: 1 },
          { word: "মাছ", parts: ["মা", "ছ"], minLevel: 1 },
          { word: "ফল", parts: ["ফ", "ল"], minLevel: 1 },
          { word: "আম", parts: ["আ", "ম"], minLevel: 1 },
          { word: "ভাত", parts: ["ভা", "ত"], minLevel: 1 },
          { word: "ঘর", parts: ["ঘ", "র"], minLevel: 1 },
          { word: "পথ", parts: ["প", "থ"], minLevel: 1 },
          { word: "ফুল", parts: ["ফু", "ল"], minLevel: 1 },
          { word: "পাখি", parts: ["পা", "খি"], minLevel: 1 },
          { word: "নদী", parts: ["ন", "দী"], minLevel: 1 },
          { word: "সাপ", parts: ["সা", "প"], minLevel: 1 },
          { word: "বাবা", parts: ["বা", "বা"], minLevel: 1 },
          { word: "মা", parts: ["মা"], minLevel: 1 },
          { word: "ভাই", parts: ["ভা", "ই"], minLevel: 1 },
          { word: "বোন", parts: ["বো", "ন"], minLevel: 1 },
          { word: "লাল", parts: ["লা", "ল"], minLevel: 1 },
          { word: "নীল", parts: ["নী", "ল"], minLevel: 1 },
          { word: "দিন", parts: ["দি", "ন"], minLevel: 1 },
          { word: "রাত", parts: ["রা", "ত"], minLevel: 1 },
          { word: "কান", parts: ["কা", "ন"], minLevel: 1 },
          { word: "নাক", parts: ["না", "ক"], minLevel: 1 },
          { word: "চোখ", parts: ["চো", "খ"], minLevel: 1 },
          { word: "হাত", parts: ["হা", "ত"], minLevel: 1 },
          { word: "পা", parts: ["পা"], minLevel: 1 },
          { word: "চুল", parts: ["চু", "ল"], minLevel: 1 },
          { word: "দেশ", parts: ["দে", "শ"], minLevel: 1 },
          { word: "নাম", parts: ["না", "ম"], minLevel: 1 },
          { word: "আলো", parts: ["আ", "লো"], minLevel: 1 },
          { word: "ছোট", parts: ["ছো", "ট"], minLevel: 1 },
          { word: "বড়", parts: ["ব", "ড়"], minLevel: 1 },
          { word: "ভালো", parts: ["ভা", "লো"], minLevel: 1 },
          { word: "গান", parts: ["গা", "ন"], minLevel: 1 },
          { word: "ছবি", parts: ["ছ", "বি"], minLevel: 1 },
          { word: "বল", parts: ["ব", "ল"], minLevel: 1 },
          { word: "গাছ", parts: ["গা", "ছ"], minLevel: 1 },
          { word: "রাজা", parts: ["রা", "জা"], minLevel: 1 },
          { word: "রাণী", parts: ["রা", "ণী"], minLevel: 1 },
          { word: "টাকা", parts: ["টা", "কা"], minLevel: 1 },
          { word: "কলা", parts: ["ক", "লা"], minLevel: 1 },
          { word: "পাতা", parts: ["পা", "তা"], minLevel: 1 },
          { word: "আগুন", parts: ["আ", "গু", "ন"], minLevel: 1 },
          { word: "মেঘ", parts: ["মে", "ঘ"], minLevel: 1 },
          { word: "রং", parts: ["র", "ং"], minLevel: 1 },
          { word: "শহর", parts: ["শ", "হ", "র"], minLevel: 1 },
          { word: "গ্রাম", parts: ["গ্রা", "ম"], minLevel: 1 },
          { word: "ভাষা", parts: ["ভা", "ষা"], minLevel: 1 },
          { word: "কাজ", parts: ["কা", "জ"], minLevel: 1 },
          { word: "কালো", parts: ["কা", "লো"], minLevel: 1 },
          { word: "সাদা", parts: ["সা", "দা"], minLevel: 1 },
          { word: "সবুজ", parts: ["স", "বু", "জ"], minLevel: 1 },
          { word: "হলুদ", parts: ["হ", "লু", "দ"], minLevel: 1 },
          { word: "রাখা", parts: ["রা", "খা"], minLevel: 1 },
          { word: "লেখা", parts: ["লে", "খা"], minLevel: 1 },
          { word: "পড়া", parts: ["প", "ড়া"], minLevel: 1 },
          { word: "বলা", parts: ["ব", "লা"], minLevel: 1 },
          { word: "শোনা", parts: ["শো", "না"], minLevel: 1 },
          { word: "দেখা", parts: ["দে", "খা"], minLevel: 1 },
          { word: "আসা", parts: ["আ", "সা"], minLevel: 1 },
          { word: "যাওয়া", parts: ["যা", "ও", "য়া"], minLevel: 1 },
          { word: "খাওয়া", parts: ["খা", "ও", "য়া"], minLevel: 1 },
          { word: "করা", parts: ["ক", "রা"], minLevel: 1 },
          { word: "চলা", parts: ["চ", "লা"], minLevel: 1 },
          { word: "থামা", parts: ["থা", "মা"], minLevel: 1 },
          { word: "জানা", parts: ["জা", "না"], minLevel: 1 },
          { word: "বোঝা", parts: ["বো", "ঝা"], minLevel: 1 },
          { word: "হাসা", parts: ["হা", "সা"], minLevel: 1 },
          { word: "কাঁদা", parts: ["কাঁ", "দা"], minLevel: 1 },
          { word: "ওঠা", parts: ["ও", "ঠা"], minLevel: 1 },
          { word: "বসা", parts: ["ব", "সা"], minLevel: 1 },
          { word: "শোয়া", parts: ["শো", "য়া"], minLevel: 1 },
          { word: "ঘুম", parts: ["ঘু", "ম"], minLevel: 1 },
          { word: "কথা", parts: ["ক", "থা"], minLevel: 1 },
          { word: "কষ্ট", parts: ["ক", "ষ্ট"], minLevel: 1 },
          { word: "সুখ", parts: ["সু", "খ"], minLevel: 1 },
          { word: "মন", parts: ["ম", "ন"], minLevel: 1 },
          { word: "প্রেম", parts: ["প্রে", "ম"], minLevel: 1 },
          { word: "ভয়", parts: ["ভ", "য়"], minLevel: 1 },
          { word: "রাগ", parts: ["রা", "গ"], minLevel: 1 },
          { word: "লোভ", parts: ["লো", "ভ"], minLevel: 1 },
          { word: "আশা", parts: ["আ", "শা"], minLevel: 1 },
          { word: "মাটি", parts: ["মা", "টি"], minLevel: 1 },
          { word: "পাথর", parts: ["পা", "থ", "র"], minLevel: 1 },
          { word: "ইট", parts: ["ই", "ট"], minLevel: 1 },
          { word: "কাঠ", parts: ["কা", "ঠ"], minLevel: 1 },
          { word: "বাঁশ", parts: ["বাঁ", "শ"], minLevel: 1 },
          { word: "সোনা", parts: ["সো", "না"], minLevel: 1 },
          { word: "রূপা", parts: ["রূ", "পা"], minLevel: 1 },
          { word: "লোহা", parts: ["লো", "হা"], minLevel: 1 },
          { word: "কাপ", parts: ["কা", "প"], minLevel: 1 },
          { word: "গ্লাস", parts: ["গ্লা", "স"], minLevel: 1 },
          { word: "থালা", parts: ["থা", "লা"], minLevel: 1 },
          { word: "বাটি", parts: ["বা", "টি"], minLevel: 1 },
          { word: "চাবি", parts: ["চা", "বি"], minLevel: 1 },
          { word: "তালা", parts: ["তা", "লা"], minLevel: 1 },
          { word: "মোম", parts: ["মো", "ম"], minLevel: 1 },
          { word: "সূর্য", parts: ["সূ", "র্য"], minLevel: 1 },
          { word: "চাঁদ", parts: ["চাঁ", "দ"], minLevel: 1 },
          { word: "তারা", parts: ["তা", "রা"], minLevel: 1 },
          { word: "গ্রহ", parts: ["গ্র", "হ"], minLevel: 1 },
          { word: "অজানা", parts: ["অ", "জা", "না"], minLevel: 1 },
          { word: "অচেনা", parts: ["অ", "চে", "না"], minLevel: 1 },
          { word: "অবাক", parts: ["অ", "বা", "ক"], minLevel: 1 },
          { word: "অনেক", parts: ["অ", "নে", "ক"], minLevel: 1 },
          { word: "অন্য", parts: ["অ", "ন্য"], minLevel: 1 },
          { word: "অল্প", parts: ["অ", "ল্প"], minLevel: 1 },
          { word: "আস্তে", parts: ["আ", "স্তে"], minLevel: 1 },
          { word: "আসল", parts: ["আ", "স", "ল"], minLevel: 1 },
          { word: "আলাদা", parts: ["আ", "লা", "দা"], minLevel: 1 },
          { word: "ইচ্ছা", parts: ["ই", "চ্ছা"], minLevel: 1 },
          { word: "উপর", parts: ["উ", "প", "র"], minLevel: 1 },
          { word: "এখন", parts: ["এ", "খ", "ন"], minLevel: 1 },
          { word: "তখন", parts: ["ত", "খ", "ন"], minLevel: 1 },
          { word: "যখন", parts: ["য", "খ", "ন"], minLevel: 1 },
          { word: "কখন", parts: ["ক", "খ", "ন"], minLevel: 1 },
          { word: "এখানে", parts: ["এ", "খা", "নে"], minLevel: 1 },
          { word: "ওখানে", parts: ["ও", "খা", "নে"], minLevel: 1 },
          { word: "সেখানে", parts: ["সে", "খা", "নে"], minLevel: 1 },
          { word: "যেখানে", parts: ["যে", "খা", "নে"], minLevel: 1 },
          { word: "কোথায়", parts: ["কো", "থা", "য়"], minLevel: 1 },
          { word: "কারণ", parts: ["কা", "র", "ণ"], minLevel: 1 },
          { word: "জন্য", parts: ["জ", "ন্য"], minLevel: 1 },
          { word: "কিন্তু", parts: ["কি", "ন্তু"], minLevel: 1 },
          { word: "অথবা", parts: ["অ", "থ", "বা"], minLevel: 1 },
          { word: "এবং", parts: ["এ", "বং"], minLevel: 1 },
          { word: "ও", parts: ["ও"], minLevel: 1 },
          { word: "আর", parts: ["আ", "র"], minLevel: 1 },
          { word: "থেকে", parts: ["থে", "কে"], minLevel: 1 },
          { word: "সাথে", parts: ["সা", "থে"], minLevel: 1 },
          { word: "মধ্যে", parts: ["ম", "ধ্যে"], minLevel: 1 },
          { word: "বাইরে", parts: ["বা", "ই", "রে"], minLevel: 1 },
          { word: "ভিতরে", parts: ["ভি", "ত", "রে"], minLevel: 1 },
          { word: "সামনে", parts: ["সা", "ম", "নে"], minLevel: 1 },
          { word: "পিছনে", parts: ["পি", "ছ", "নে"], minLevel: 1 },
          { word: "ডানে", parts: ["ডা", "নে"], minLevel: 1 },
          { word: "বামে", parts: ["বা", "মে"], minLevel: 1 },
          { word: "তাহলে", parts: ["তা", "হ", "লে"], minLevel: 1 },
          { word: "হয়তো", parts: ["হ", "য়", "তো"], minLevel: 1 },
          { word: "অবশ্যই", parts: ["অ", "ব", "শ্য", "ই"], minLevel: 1 },
          { word: "আবার", parts: ["আ", "বা", "র"], minLevel: 1 },
          { word: "প্রায়", parts: ["প্রা", "য়"], minLevel: 1 },
          { word: "কিছু", parts: ["কি", "ছু"], minLevel: 1 },
          { word: "সব", parts: ["স", "ব"], minLevel: 1 },
          { word: "কেউ", parts: ["কে", "উ"], minLevel: 1 },
          { word: "নিজের", parts: ["নি", "জে", "র"], minLevel: 1 },
          { word: "পর্যন্ত", parts: ["প", "র্য", "ন্ত"], minLevel: 1 },
          { word: "হঠাৎ", parts: ["হ", "ঠা", "ৎ"], minLevel: 1 },
          { word: "আসলে", parts: ["আ", "স", "লে"], minLevel: 1 },
          { word: "বোকা", parts: ["বো", "কা"], minLevel: 1 },
          { word: "অলস", parts: ["অ", "ল", "স"], minLevel: 1 },
          { word: "রোগা", parts: ["রো", "গা"], minLevel: 1 },
          { word: "লম্বা", parts: ["ল", "ম্বা"], minLevel: 1 },
          { word: "খাটো", parts: ["খা", "টো"], minLevel: 1 },
          { word: "মোটা", parts: ["মো", "টা"], minLevel: 1 },
          { word: "চিকন", parts: ["চি", "ক", "ন"], minLevel: 1 },
          { word: "গরম", parts: ["গ", "র", "ম"], minLevel: 1 },
          { word: "ঠান্ডা", parts: ["ঠা", "ন্ডা"], minLevel: 1 },
          { word: "হালকা", parts: ["হা", "ল", "কা"], minLevel: 1 },
          { word: "ভারী", parts: ["ভা", "রী"], minLevel: 1 },
          { word: "নরম", parts: ["ন", "র", "ম"], minLevel: 1 },
          { word: "শক্ত", parts: ["শ", "ক্ত"], minLevel: 1 },
          { word: "মিষ্টি", parts: ["মি", "ষ্টি"], minLevel: 1 },
          { word: "টক", parts: ["ট", "ক"], minLevel: 1 },
          { word: "ঝাল", parts: ["ঝা", "ল"], minLevel: 1 },
          { word: "নোনতা", parts: ["নো", "ন", "তা"], minLevel: 1 },
          { word: "সহজ", parts: ["স", "হ", "জ"], minLevel: 1 },
          { word: "কঠিন", parts: ["ক", "ঠি", "ন"], minLevel: 1 },
          { word: "ধীরে", parts: ["ধী", "রে"], minLevel: 1 },
          { word: "কাছে", parts: ["কা", "ছে"], minLevel: 1 },
          { word: "দূরে", parts: ["দূ", "রে"], minLevel: 1 },
          { word: "আজ", parts: ["আ", "জ"], minLevel: 1 },
          { word: "কাল", parts: ["কা", "ল"], minLevel: 1 },
          { word: "ভুল", parts: ["ভু", "ল"], minLevel: 1 },
          { word: "সঠিক", parts: ["স", "ঠি", "ক"], minLevel: 1 },
          { word: "দোষ", parts: ["দো", "ষ"], minLevel: 1 },
          { word: "গুণ", parts: ["গু", "ণ"], minLevel: 1 },
          { word: "মিল", parts: ["মি", "ল"], minLevel: 1 },
          { word: "শুরু", parts: ["শু", "রু"], minLevel: 1 },
          { word: "শেষ", parts: ["শে", "ষ"], minLevel: 1 },
          { word: "চিনি", parts: ["চি", "নি"], minLevel: 1 },
          { word: "লবণ", parts: ["ল", "ব", "ণ"], minLevel: 1 },
          { word: "দুধ", parts: ["দু", "ধ"], minLevel: 1 },
          { word: "ডিম", parts: ["ডি", "ম"], minLevel: 1 },
          { word: "তেল", parts: ["তে", "ল"], minLevel: 1 },
          { word: "লেবু", parts: ["লে", "বু"], minLevel: 1 },

          // --- Level 2 (মাঝারি শব্দ, পরিচিত) ---
          { word: "আলমারি", parts: ["আ", "ল", "মা", "রি"], minLevel: 2 },
          { word: "টেবিল", parts: ["টে", "বি", "ল"], minLevel: 2 },
          { word: "চেয়ার", parts: ["চে", "য়া", "র"], minLevel: 2 },
          { word: "বিছানা", parts: ["বি", "ছা", "না"], minLevel: 2 },
          { word: "দরজা", parts: ["দ", "র", "জা"], minLevel: 2 },
          { word: "জানালা", parts: ["জা", "না", "লা"], minLevel: 2 },
          { word: "দেয়াল", parts: ["দে", "য়া", "ল"], minLevel: 2 },
          { word: "বারান্দা", parts: ["বা", "রা", "ন্দা"], minLevel: 2 },
          { word: "রান্নাঘর", parts: ["রা", "ন্না", "ঘ", "র"], minLevel: 2 },
          { word: "বাথরুম", parts: ["বা", "থ", "রু", "ম"], minLevel: 2 },
          { word: "কাপড়", parts: ["কা", "প", "ড়"], minLevel: 2 },
          { word: "গয়না", parts: ["গ", "য়", "না"], minLevel: 2 },
          { word: "চশমা", parts: ["চ", "শ", "মা"], minLevel: 2 },
          { word: "ঘড়ি", parts: ["ঘ", "ড়ি"], minLevel: 2 },
          { word: "আয়না", parts: ["আ", "য়", "না"], minLevel: 2 },
          { word: "চিরুনি", parts: ["চি", "রু", "নি"], minLevel: 2 },
          { word: "সাবান", parts: ["সা", "বা", "ন"], minLevel: 2 },
          { word: "তোয়ালে", parts: ["তো", "য়া", "লে"], minLevel: 2 },
          { word: "বিড়াল", parts: ["বি", "ড়া", "ল"], minLevel: 2 },
          { word: "কুকুর", parts: ["কু", "কু", "র"], minLevel: 2 },
          { word: "গরু", parts: ["গ", "রু"], minLevel: 2 },
          { word: "ছাগল", parts: ["ছা", "গ", "ল"], minLevel: 2 },
          { word: "হাঁস", parts: ["হাঁ", "স"], minLevel: 2 },
          { word: "মুরগি", parts: ["মু", "র", "গি"], minLevel: 2 },
          { word: "কবুতর", parts: ["ক", "বু", "ত", "র"], minLevel: 2 },
          { word: "মানুষ", parts: ["মা", "নু", "ষ"], minLevel: 2 },
          { word: "ছেলে", parts: ["ছে", "লে"], minLevel: 2 },
          { word: "মেয়ে", parts: ["মে", "য়ে"], minLevel: 2 },
          { word: "শিশু", parts: ["শি", "শু"], minLevel: 2 },
          { word: "শিক্ষক", parts: ["শি", "ক্ষ", "ক"], minLevel: 2 },
          { word: "ছাত্র", parts: ["ছা", "ত্র"], minLevel: 2 },
          { word: "বন্ধু", parts: ["ব", "ন্ধু"], minLevel: 2 },
          { word: "আত্মীয়", parts: ["আ", "ত্মী", "য়"], minLevel: 2 },
          { word: "প্রতিবেশী", parts: ["প্র", "তি", "বে", "শী"], minLevel: 2 },
          { word: "দোকানদার", parts: ["দো", "কা", "ন", "দা", "র"], minLevel: 2 },
          { word: "ক্রেতা", parts: ["ক্রে", "তা"], minLevel: 2 },
          { word: "বিক্রেতা", parts: ["বি", "ক্রে", "তা"], minLevel: 2 },
          { word: "ডাক্তার", parts: ["ডা", "ক্তা", "র"], minLevel: 2 },
          { word: "উকিল", parts: ["উ", "কি", "ল"], minLevel: 2 },
          { word: "পুলিশ", parts: ["পু", "লি", "শ"], minLevel: 2 },
          { word: "চাষী", parts: ["চা", "ষী"], minLevel: 2 },
          { word: "জেলে", parts: ["জে", "লে"], minLevel: 2 },
          { word: "কামার", parts: ["কা", "মা", "র"], minLevel: 2 },
          { word: "কুমার", parts: ["কু", "মা", "র"], minLevel: 2 },
          { word: "তাঁতি", parts: ["তাঁ", "তি"], minLevel: 2 },
          { word: "বাজার", parts: ["বা", "জা", "র"], minLevel: 2 },
          { word: "দোকান", parts: ["দো", "কা", "ন"], minLevel: 2 },
          { word: "রাস্তা", parts: ["রা", "স্তা"], minLevel: 2 },
          { word: "গাড়ি", parts: ["গা", "ড়ি"], minLevel: 2 },
          { word: "রিকশা", parts: ["রি", "ক", "শা"], minLevel: 2 },
          { word: "সাইকেল", parts: ["সা", "ই", "কে", "ল"], minLevel: 2 },
          { word: "বিমান", parts: ["বি", "মা", "ন"], minLevel: 2 },
          { word: "জাহাজ", parts: ["জা", "হা", "জ"], minLevel: 2 },
          { word: "নৌকা", parts: ["নৌ", "কা"], minLevel: 2 },
          { word: "ট্রেন", parts: ["ট্রে", "ন"], minLevel: 2 },
          { word: "স্টেশন", parts: ["স্টে", "শ", "ন"], minLevel: 2 },
          { word: "অফিস", parts: ["অ", "ফি", "স"], minLevel: 2 },
          { word: "কারখানা", parts: ["কা", "র", "খা", "না"], minLevel: 2 },
          { word: "খাবার", parts: ["খা", "বা", "র"], minLevel: 2 },
          { word: "সকাল", parts: ["স", "কা", "ল"], minLevel: 2 },
          { word: "দুপুর", parts: ["দু", "পু", "র"], minLevel: 2 },
          { word: "বিকাল", parts: ["বি", "কা", "ল"], minLevel: 2 },
          { word: "সন্ধ্যা", parts: ["স", "ন্ধ্যা"], minLevel: 2 },
          { word: "আকাশ", parts: ["আ", "কা", "শ"], minLevel: 2 },
          { word: "বাতাস", parts: ["বা", "তা", "স"], minLevel: 2 },
          { word: "বৃষ্টি", parts: ["বৃ", "ষ্টি"], minLevel: 2 },
          { word: "রোদ", parts: ["রো", "দ"], minLevel: 2 },
          { word: "পৃথিবী", parts: ["পৃ", "থি", "বী"], minLevel: 2 },
          { word: "সমুদ্র", parts: ["স", "মু", "দ্র"], minLevel: 2 },
          { word: "পাহাড়", parts: ["পা", "হা", "ড়"], minLevel: 2 },
          { word: "জঙ্গল", parts: ["জ", "ঙ্গ", "ল"], minLevel: 2 },
          { word: "বাগান", parts: ["বা", "গা", "ন"], minLevel: 2 },
          { word: "মাঠ", parts: ["মা", "ঠ"], minLevel: 2 },
          { word: "পুকুর", parts: ["পু", "কু", "র"], minLevel: 2 },
          { word: "কমলা", parts: ["ক", "ম", "লা"], minLevel: 2 },
          { word: "আপেল", parts: ["আ", "পে", "ল"], minLevel: 2 },
          { word: "পেঁপে", parts: ["পেঁ", "পে"], minLevel: 2 },
          { word: "আনারস", parts: ["আ", "না", "র", "স"], minLevel: 2 },
          { word: "তরমুজ", parts: ["ত", "র", "মু", "জ"], minLevel: 2 },
          { word: "লিচু", parts: ["লি", "চু"], minLevel: 2 },
          { word: "পেয়ারা", parts: ["পে", "য়া", "রা"], minLevel: 2 },
          { word: "আলু", parts: ["আ", "লু"], minLevel: 2 },
          { word: "বেগুন", parts: ["বে", "গু", "ন"], minLevel: 2 },
          { word: "পেঁয়াজ", parts: ["পেঁ", "য়া", "জ"], minLevel: 2 },
          { word: "রসুন", parts: ["র", "সু", "ন"], minLevel: 2 },
          { word: "আদা", parts: ["আ", "দা"], minLevel: 2 },
          { word: "মরিচ", parts: ["ম", "রি", "চ"], minLevel: 2 },
          { word: "সবজি", parts: ["স", "ব", "জি"], minLevel: 2 },
          { word: "মসলা", parts: ["ম", "স", "লা"], minLevel: 2 },
          { word: "চিঠি", parts: ["চি", "ঠি"], minLevel: 2 },
          { word: "খবর", parts: ["খ", "ব", "র"], minLevel: 2 },
          { word: "কাগজ", parts: ["কা", "গ", "জ"], minLevel: 2 },
          { word: "লেখক", parts: ["লে", "খ", "ক"], minLevel: 2 },
          { word: "কবি", parts: ["ক", "বি"], minLevel: 2 },
          { word: "গল্প", parts: ["গ", "ল্প"], minLevel: 2 },
          { word: "কবিতা", parts: ["ক", "বি", "তা"], minLevel: 2 },
          { word: "উপন্যাস", parts: ["উ", "প", "ন্যা", "স"], minLevel: 2 },
          { word: "নাটক", parts: ["না", "ট", "ক"], minLevel: 2 },
          { word: "সিনেমা", parts: ["সি", "নে", "মা"], minLevel: 2 },
          { word: "সুন্দর", parts: ["সু", "ন্দ", "র"], minLevel: 2 },
          { word: "অন্ধকার", parts: ["অ", "ন্ধ", "কা", "র"], minLevel: 2 },
          { word: "আলোচনা", parts: ["আ", "লো", "চ", "না"], minLevel: 2 },
          { word: "বিদ্যালয়", parts: ["বি", "দ্যা", "ল", "য়"], minLevel: 2 },
          { word: "পড়ালেখা", parts: ["প", "ড়া", "লে", "খা"], minLevel: 2 },
          { word: "পরীক্ষা", parts: ["প", "রী", "ক্ষা"], minLevel: 2 },
          { word: "ফলাফল", parts: ["ফ", "লা", "ফ", "ল"], minLevel: 2 },
          { word: "হাসপাতাল", parts: ["হা", "স", "পা", "তা", "ল"], minLevel: 2 },
          { word: "ঔষধ", parts: ["ঔ", "ষ", "ধ"], minLevel: 2 },
          { word: "অসুস্থ", parts: ["অ", "সু", "স্থ"], minLevel: 2 },
          { word: "স্বাস্থ্য", parts: ["স্বা", "স্থ্য"], minLevel: 2 },
          { word: "পরিষ্কার", parts: ["প", "রি", "ষ্কা", "র"], minLevel: 2 },
          { word: "আবর্জনা", parts: ["আ", "ব", "র্জ", "না"], minLevel: 2 },
          { word: "পরিবেশ", parts: ["প", "রি", "বে", "শ"], minLevel: 2 },
          { word: "প্রকৃতি", parts: ["প্র", "কৃ", "তি"], minLevel: 2 },
          { word: "আনন্দ", parts: ["আ", "ন", "ন্দ"], minLevel: 2 },
          { word: "উৎসব", parts: ["উ", "ৎস", "ব"], minLevel: 2 },
          { word: "অনুষ্ঠান", parts: ["অ", "নু", "ষ্ঠা", "ন"], minLevel: 2 },
          { word: "বিবাহ", parts: ["বি", "বা", "হ"], minLevel: 2 },
          { word: "জন্মদিন", parts: ["জ", "ন্ম", "দি", "ন"], minLevel: 2 },
          { word: "খেলাধুলা", parts: ["খে", "লা", "ধু", "লা"], minLevel: 2 },
          { word: "ক্রিকেট", parts: ["ক্রি", "কে", "ট"], minLevel: 2 },
          { word: "ফুটবল", parts: ["ফু", "ট", "ব", "ল"], minLevel: 2 },
          { word: "সংখ্যা", parts: ["সং", "খ্যা"], minLevel: 2 },
          { word: "সময়", parts: ["স", "ম", "য়"], minLevel: 2 },
          { word: "ভবিষ্যৎ", parts: ["ভ", "বি", "ষ্য", "ৎ"], minLevel: 2 },
          { word: "বর্তমান", parts: ["ব", "র্ত", "মা", "ন"], minLevel: 2 },
          { word: "অতীত", parts: ["অ", "তী", "ত"], minLevel: 2 },
          { word: "শরীর", parts: ["শ", "রী", "র"], minLevel: 2 },
          { word: "প্রশ্ন", parts: ["প্র", "শ্ন"], minLevel: 2 },
          { word: "উত্তর", parts: ["উ", "ত্ত", "র"], minLevel: 2 },
          { word: "শব্দ", parts: ["শ", "ব্দ"], minLevel: 2 },
          { word: "বাক্য", parts: ["বা", "ক্য"], minLevel: 2 },
          { word: "শিক্ষা", parts: ["শি", "ক্ষা"], minLevel: 2 },
          { word: "হাতি", parts: ["হা", "তি"], minLevel: 2 },
          { word: "ঘোড়া", parts: ["ঘো", "ড়া"], minLevel: 2 },
          { word: "বাঘ", parts: ["বা", "ঘ"], minLevel: 2 },
          { word: "সিংহ", parts: ["সিং", "হ"], minLevel: 2 },
          { word: "ভালুক", parts: ["ভা", "লু", "ক"], minLevel: 2 },
          { word: "হরিণ", parts: ["হ", "রি", "ণ"], minLevel: 2 },
          { word: "শিয়াল", parts: ["শি", "য়া", "ল"], minLevel: 2 },
          { word: "টিকটিকি", parts: ["টি", "ক", "টি", "কি"], minLevel: 2 },
          { word: "মশা", parts: ["ম", "শা"], minLevel: 2 },
          { word: "মাছি", parts: ["মা", "ছি"], minLevel: 2 },
          { word: "মৌমাছি", parts: ["মৌ", "মা", "ছি"], minLevel: 2 },
          { word: "পিপীলিকা", parts: ["পি", "পী", "লি", "কা"], minLevel: 2 },
          { word: "তেলাপোকা", parts: ["তে", "লা", "পো", "কা"], minLevel: 2 },
          { word: "প্রজাপতি", parts: ["প্র", "জা", "প", "তি"], minLevel: 2 },
          { word: "ফড়িং", parts: ["ফ", "ড়ি", "ং"], minLevel: 2 },
          { word: "শামুক", parts: ["শা", "মু", "ক"], minLevel: 2 },
          { word: "কেঁচো", parts: ["কেঁ", "চো"], minLevel: 2 },
          { word: "ব্যাঙ", parts: ["ব্যা", "ঙ"], minLevel: 2 },
          { word: "কুমির", parts: ["কু", "মি", "র"], minLevel: 2 },
          { word: "কচ্ছপ", parts: ["ক", "চ্ছ", "প"], minLevel: 2 },
          { word: "কাঁকড়া", parts: ["কাঁ", "ক", "ড়া"], minLevel: 2 },
          { word: "চিংড়ি", parts: ["চিং", "ড়ি"], minLevel: 2 },
          { word: "ইলিশ", parts: ["ই", "লি", "শ"], minLevel: 2 },
          { word: "রুই", parts: ["রু", "ই"], minLevel: 2 },
          { word: "কাতলা", parts: ["কা", "ত", "লা"], minLevel: 2 },
          { word: "পায়রা", parts: ["পা", "য়", "রা"], minLevel: 2 },
          { word: "টিয়া", parts: ["টি", "য়া"], minLevel: 2 },
          { word: "ময়না", parts: ["ম", "য়", "না"], minLevel: 2 },
          { word: "শালিক", parts: ["শা", "লি", "ক"], minLevel: 2 },
          { word: "কাক", parts: ["কা", "ক"], minLevel: 2 },
          { word: "কোকিল", parts: ["কো", "কি", "ল"], minLevel: 2 },
          { word: "চড়ুই", parts: ["চ", "ড়ু", "ই"], minLevel: 2 },
          { word: "ইগল", parts: ["ই", "গ", "ল"], minLevel: 2 },
          { word: "শকুন", parts: ["শ", "কু", "ন"], minLevel: 2 },
          { word: "পেঁচা", parts: ["পেঁ", "চা"], minLevel: 2 },
          { word: "বাদুড়", parts: ["বা", "দু", "ড়"], minLevel: 2 },
          { word: "কাঠবিড়ালী", parts: ["কা", "ঠ", "বি", "ড়া", "লী"], minLevel: 2 },
          { word: "বানর", parts: ["বা", "ন", "র"], minLevel: 2 },
          { word: "জিরাফ", parts: ["জি", "রা", "ফ"], minLevel: 2 },
          { word: "জেব্রা", parts: ["জে", "ব্রা"], minLevel: 2 },
          { word: "সপ্তাহ", parts: ["স", "প্তা", "হ"], minLevel: 2 },
          { word: "মাস", parts: ["মা", "স"], minLevel: 2 },
          { word: "বছর", parts: ["ব", "ছ", "র"], minLevel: 2 },
          { word: "শনিবার", parts: ["শ", "নি", "বা", "র"], minLevel: 2 },
          { word: "রবিবার", parts: ["র", "বি", "বা", "র"], minLevel: 2 },
          { word: "সোমবার", parts: ["সো", "ম", "বা", "র"], minLevel: 2 },
          { word: "মঙ্গলবার", parts: ["ম", "ঙ্গ", "ল", "বা", "র"], minLevel: 2 },
          { word: "বুধবার", parts: ["বু", "ধ", "বা", "র"], minLevel: 2 },
          { word: "সরকার", parts: ["স", "র", "কা", "র"], minLevel: 2 },
          { word: "আইন", parts: ["আ", "ই", "ন"], minLevel: 2 },
          { word: "বিচার", parts: ["বি", "চা", "র"], minLevel: 2 },
          { word: "শাস্তি", parts: ["শা", "স্তি"], minLevel: 2 },
          { word: "অপরাধ", parts: ["অ", "প", "রা", "ধ"], minLevel: 2 },
          { word: "শান্তি", parts: ["শা", "ন্তি"], minLevel: 2 },
          { word: "যুদ্ধ", parts: ["যু", "দ্ধ"], minLevel: 2 },
          { word: "সৈন্য", parts: ["সৈ", "ন্য"], minLevel: 2 },
          { word: "অস্ত্র", parts: ["অ", "স্ত্র"], minLevel: 2 },
          { word: "পতাকা", parts: ["প", "তা", "কা"], minLevel: 2 },
          { word: "জাতি", parts: ["জা", "তি"], minLevel: 2 },
          { word: "ধর্ম", parts: ["ধ", "র্ম"], minLevel: 2 },
          { word: "বিশ্বাস", parts: ["বি", "শ্বা", "স"], minLevel: 2 },
          { word: "প্রার্থনা", parts: ["প্রা", "র্থ", "না"], minLevel: 2 },
          { word: "মন্দির", parts: ["ম", "ন্দি", "র"], minLevel: 2 },
          { word: "মসজিদ", parts: ["ম", "স", "জি", "দ"], minLevel: 2 },
          { word: "গীর্জা", parts: ["গী", "র্জা"], minLevel: 2 },
          { word: "প্যাগোডা", parts: ["প্যা", "গো", "ডা"], minLevel: 2 },
          { word: "বিজ্ঞান", parts: ["বি", "জ্ঞা", "ন"], minLevel: 2 },
          { word: "গণিত", parts: ["গ", "ণি", "ত"], minLevel: 2 },
          { word: "ইতিহাস", parts: ["ই", "তি", "হা", "স"], minLevel: 2 },
          { word: "ভূগোল", parts: ["ভূ", "গো", "ল"], minLevel: 2 },
          { word: "নাগরিক", parts: ["না", "গ", "রি", "ক"], minLevel: 2 },
          { word: "দুনিয়া", parts: ["দু", "নি", "য়া"], minLevel: 2 },
          { word: "অঞ্চল", parts: ["অ", "ঞ্চ", "ল"], minLevel: 2 },
          { word: "রাজধানী", parts: ["রা", "জ", "ধা", "নী"], minLevel: 2 },
          { word: "বন্দর", parts: ["ব", "ন্দ", "র"], minLevel: 2 },
          { word: "সীমান্ত", parts: ["সী", "মা", "ন্ত"], minLevel: 2 },
          { word: "ব্যাপার", parts: ["ব্যা", "পা", "র"], minLevel: 2 },
          { word: "সমস্যা", parts: ["স", "ম", "স্যা"], minLevel: 2 },
          { word: "সমাধান", parts: ["স", "মা", "ধা", "ন"], minLevel: 2 },
          { word: "সাহায্য", parts: ["সা", "হা", "য্য"], minLevel: 2 },
          { word: "পরামর্শ", parts: ["প", "রা", "ম", "র্শ"], minLevel: 2 },
          { word: "উপদেশ", parts: ["উ", "প", "দে", "শ"], minLevel: 2 },
          { word: "নির্দেশ", parts: ["নি", "র্দে", "শ"], minLevel: 2 },
          { word: "অনুরোধ", parts: ["অ", "নু", "রো", "ধ"], minLevel: 2 },
          { word: "আদেশ", parts: ["আ", "দে", "শ"], minLevel: 2 },
          { word: "ক্ষমা", parts: ["ক্ষ", "মা"], minLevel: 2 },
          { word: "ধন্যবাদ", parts: ["ধ", "ন্য", "বা", "দ"], minLevel: 2 },
          { word: "দুঃখিত", parts: ["দুঃ", "খি", "ত"], minLevel: 2 },
          { word: "স্বাগতম", parts: ["স্বা", "গ", "ত", "ম"], minLevel: 2 },
          { word: "বিদায়", parts: ["বি", "দা", "য়"], minLevel: 2 },
          { word: "অবসর", parts: ["অ", "ব", "স", "র"], minLevel: 2 },
          { word: "ছুটি", parts: ["ছু", "টি"], minLevel: 2 },
          { word: "বেতন", parts: ["বে", "ত", "ন"], minLevel: 2 },
          { word: "চাকরি", parts: ["চা", "ক", "রি"], minLevel: 2 },
          { word: "ব্যবসা", parts: ["ব্য", "ব", "সা"], minLevel: 2 },
          { word: "লাভ", parts: ["লা", "ভ"], minLevel: 2 },
          { word: "ক্ষতি", parts: ["ক্ষ", "তি"], minLevel: 2 },
          { word: "আয়", parts: ["আ", "য়"], minLevel: 2 },
          { word: "ব্যয়", parts: ["ব্য", "য়"], minLevel: 2 },
          { word: "সঞ্চয়", parts: ["স", "ঞ্চ", "য়"], minLevel: 2 },
          { word: "ঋণ", parts: ["ঋ", "ণ"], minLevel: 2 },
          { word: "বাজেট", parts: ["বা", "জে", "ট"], minLevel: 2 },
          { word: "পরিকল্পনা", parts: ["প", "রি", "ক", "ল্প", "না"], minLevel: 2 },
          { word: "উন্নয়ন", parts: ["উ", "ন্ন", "য়", "ন"], minLevel: 2 },
          { word: "অগ্রগতি", parts: ["অ", "গ্র", "গ", "তি"], minLevel: 2 },
          { word: "পরিবর্তন", parts: ["প", "রি", "ব", "র্ত", "ন"], minLevel: 2 },
          { word: "বৃদ্ধি", parts: ["বৃ", "দ্ধি"], minLevel: 2 },
          { word: "প্রয়োজন", parts: ["প্র", "য়ো", "জ", "ন"], minLevel: 2 },
          { word: "দরকার", parts: ["দ", "র", "কা", "র"], minLevel: 2 },
          { word: "অভাব", parts: ["অ", "ভা", "ব"], minLevel: 2 },
          { word: "পর্যাপ্ত", parts: ["প", "র্যা", "প্ত"], minLevel: 2 },
          { word: "অতিরিক্ত", parts: ["অ", "তি", "রি", "ক্ত"], minLevel: 2 },
          { word: "সাধারণ", parts: ["সা", "ধা", "র", "ণ"], minLevel: 2 },
          { word: "বিশেষ", parts: ["বি", "শে", "ষ"], minLevel: 2 },
          { word: "ব্যক্তিগত", parts: ["ব্য", "ক্তি", "গ", "ত"], minLevel: 2 },
          { word: "সরকারি", parts: ["স", "র", "কা", "রি"], minLevel: 2 },
          { word: "বেসরকারি", parts: ["বে", "স", "র", "কা", "রি"], minLevel: 2 },
          { word: "দুর্বল", parts: ["দু", "র্ব", "ল"], minLevel: 2 },
          { word: "সাহসী", parts: ["সা", "হ", "সী"], minLevel: 2 },
          { word: "ভীতু", parts: ["ভী", "তু"], minLevel: 2 },
          { word: "সৎ", parts: ["স", "ৎ"], minLevel: 2 },
          { word: "অসৎ", parts: ["অ", "স", "ৎ"], minLevel: 2 },
          { word: "ধনী", parts: ["ধ", "নী"], minLevel: 2 },
          { word: "গরীব", parts: ["গ", "রী", "ব"], minLevel: 2 },
          { word: "তিক্ত", parts: ["তি", "ক্ত"], minLevel: 2 },
          { word: "দ্রুত", parts: ["দ্রু", "ত"], minLevel: 2 },
          { word: "গতকাল", parts: ["গ", "ত", "কা", "ল"], minLevel: 2 },
          { word: "অবকাশ", parts: ["অ", "ব", "কা", "শ"], minLevel: 2 },
          { word: "ভ্রমণ", parts: ["ভ্র", "ম", "ণ"], minLevel: 2 },
          { word: "অভিযান", parts: ["অ", "ভি", "যা", "ন"], minLevel: 2 },
          { word: "অনুভূতি", parts: ["অ", "নু", "ভূ", "তি"], minLevel: 2 },
          { word: "স্মৃতি", parts: ["স্মৃ", "তি"], minLevel: 2 },
          { word: "স্বপ্ন", parts: ["স্ব", "প্ন"], minLevel: 2 },
          { word: "বাস্তবতা", parts: ["বা", "স্ত", "ব", "তা"], minLevel: 2 },
          { word: "কল্পনা", parts: ["ক", "ল্প", "না"], minLevel: 2 },
          { word: "অধ্যায়", parts: ["অ", "ধ্যা", "য়"], minLevel: 2 },
          { word: "বিষয়", parts: ["বি", "ষ", "য়"], minLevel: 2 },
          { word: "সফলতা", parts: ["স", "ফ", "ল", "তা"], minLevel: 2 },
          { word: "ব্যর্থতা", parts: ["ব্য", "র্থ", "তা"], minLevel: 2 },
          { word: "সুযোগ", parts: ["সু", "যো", "গ"], minLevel: 2 },
          { word: "ঝুঁকি", parts: ["ঝুঁ", "কি"], minLevel: 2 },
          { word: "বিপদ", parts: ["বি", "প", "দ"], minLevel: 2 },
          { word: "ঘটনা", parts: ["ঘ", "ট", "না"], minLevel: 2 },
          { word: "পরিচয়", parts: ["প", "রি", "চ", "য়"], minLevel: 2 },
          { word: "পরিচিত", parts: ["প", "রি", "চি", "ত"], minLevel: 2 },
          { word: "অপরিচিত", parts: ["অ", "প", "রি", "চি", "ত"], minLevel: 2 },
          { word: "অনুমান", parts: ["অ", "নু", "মা", "ন"], minLevel: 2 },
          { word: "পেশা", parts: ["পে", "শা"], minLevel: 2 },
          { word: "নেশা", parts: ["নে", "শা"], minLevel: 2 },
          { word: "অভ্যাস", parts: ["অ", "ভ্যা", "স"], minLevel: 2 },
          { word: "আচরণ", parts: ["আ", "চ", "র", "ণ"], minLevel: 2 },
          { word: "ব্যবহার", parts: ["ব্য", "ব", "হা", "র"], minLevel: 2 },
          { word: "চরিত্র", parts: ["চ", "রি", "ত্র"], minLevel: 2 },
          { word: "সুনাম", parts: ["সু", "না", "ম"], minLevel: 2 },
          { word: "নিন্দা", parts: ["নি", "ন্দা"], minLevel: 2 },
          { word: "ইশারা", parts: ["ই", "শা", "রা"], minLevel: 2 },
          { word: "সংকেত", parts: ["সং", "কে", "ত"], minLevel: 2 },
          { word: "প্রমাণ", parts: ["প্র", "মা", "ণ"], minLevel: 2 },
          { word: "সাক্ষী", parts: ["সা", "ক্ষী"], minLevel: 2 },
          { word: "মিথ্যা", parts: ["মি", "থ্যা"], minLevel: 2 },
          { word: "সত্য", parts: ["স", "ত্য"], minLevel: 2 },
          { word: "শুদ্ধ", parts: ["শু", "দ্ধ"], minLevel: 2 },
          { word: "ত্রুটি", parts: ["ত্রু", "টি"], minLevel: 2 },
          { word: "ক্ষমতা", parts: ["ক্ষ", "ম", "তা"], minLevel: 2 },
          { word: "প্রভাব", parts: ["প্র", "ভা", "ব"], minLevel: 2 },
          { word: "সম্পর্ক", parts: ["স", "ম্প", "র্ক"], minLevel: 2 },
          { word: "আগমন", parts: ["আ", "গ", "ম", "ন"], minLevel: 2 },
          { word: "উপকার", parts: ["উ", "প", "কা", "র"], minLevel: 2 },
          { word: "অপকার", parts: ["অ", "প", "কা", "র"], minLevel: 2 },
          { word: "টীকা", parts: ["টী", "কা"], minLevel: 2 },
          { word: "ব্যাংক", parts: ["ব্যাং", "ক"], minLevel: 2 },
          { word: "নার্স", parts: ["না", "র্স"], minLevel: 2 },
          { word: "নাবিক", parts: ["না", "বি", "ক"], minLevel: 2 },
          { word: "ডুবুরি", parts: ["ডু", "বু", "রি"], minLevel: 2 },
          { word: "গায়ক", parts: ["গা", "য়", "ক"], minLevel: 2 },
          { word: "গায়িকা", parts: ["গা", "য়ি", "কা"], minLevel: 2 },
          { word: "পেন্সিল", parts: ["পেন", "সি", "ল"], minLevel: 2 },
          { word: "রাবার", parts: ["রা", "বা", "র"], minLevel: 2 },
          { word: "আদালত", parts: ["আ", "দা", "ল", "ত"], minLevel: 2 },
          { word: "শিল্পী", parts: ["শি", "ল্পী"], minLevel: 2 },

          // --- Level 3 (কিছুটা দীর্ঘ, যুক্তাক্ষরযুক্ত বা কম প্রচলিত কিন্তু জানা শব্দ) ---
          { word: "বাংলাদেশ", parts: ["বাং", "লা", "দে", "শ"], minLevel: 3 },
          { word: "টেলিভিশন", parts: ["টে", "লি", "ভি", "শ", "ন"], minLevel: 3 },
          { word: "মোটরসাইকেল", parts: ["মো", "ট", "র", "সা", "ই", "কে", "ল"], minLevel: 3 },
          { word: "কম্পিউটার", parts: ["ক", "ম্পি", "উ", "টা", "র"], minLevel: 3 },
          { word: "ইন্টারনেট", parts: ["ই", "ন্টা", "র", "নে", "ট"], minLevel: 3 },
          { word: "মোবাইল", parts: ["মো", "বা", "ই", "ল"], minLevel: 3 },
          { word: "রাজনীতি", parts: ["রা", "জ", "নী", "তি"], minLevel: 3 },
          { word: "অর্থনীতি", parts: ["অ", "র্থ", "নী", "তি"], minLevel: 3 },
          { word: "সংবিধান", parts: ["সং", "বি", "ধা", "ন"], minLevel: 3 },
          { word: "আইনজীবী", parts: ["আ", "ই", "ন", "জী", "বী"], minLevel: 3 },
          { word: "বিচারপতি", parts: ["বি", "চা", "র", "প", "তি"], minLevel: 3 },
          { word: "সাংবাদিক", parts: ["সাং", "বা", "দি", "ক"], minLevel: 3 },
          { word: "সংবাদপত্র", parts: ["সং", "বা", "দ", "প", "ত্র"], minLevel: 3 },
          { word: "সম্পাদক", parts: ["স", "ম্পা", "দ", "ক"], minLevel: 3 },
          { word: "প্রকৌশলী", parts: ["প্র", "কৌ", "শ", "লী"], minLevel: 3 },
          { word: "স্থপতি", parts: ["স্থ", "প", "তি"], minLevel: 3 },
          { word: "গবেষণা", parts: ["গ", "বে", "ষ", "ণা"], minLevel: 3 },
          { word: "উদ্ভাবন", parts: ["উ", "দ্ভা", "ব", "ন"], minLevel: 3 },
          { word: "প্রযুক্তি", parts: ["প্র", "যু", "ক্তি"], minLevel: 3 },
          { word: "অক্সিজেন", parts: ["অ", "ক্সি", "জে", "ন"], minLevel: 3 },
          { word: "কার্বন", parts: ["কা", "র্ব", "ন"], minLevel: 3 },
          { word: "হাইড্রোজেন", parts: ["হা", "ই", "ড্রো", "জে", "ন"], minLevel: 3 },
          { word: "ব্যবস্থাপনা", parts: ["ব্য", "ব", "স্থা", "প", "না"], minLevel: 3 },
          { word: "পরিচালক", parts: ["প", "রি", "চা", "ল", "ক"], minLevel: 3 },
          { word: "কর্মকর্তা", parts: ["ক", "র্ম", "ক", "র্তা"], minLevel: 3 },
          { word: "কর্মচারী", parts: ["ক", "র্ম", "চা", "রী"], minLevel: 3 },
          { word: "স্বাধীনতা", parts: ["স্বা", "ধী", "ন", "তা"], minLevel: 3 },
          { word: "প্রজাতন্ত্র", parts: ["প্র", "জা", "ত", "ন্ত্র"], minLevel: 3 },
          { word: "গণতন্ত্র", parts: ["গ", "ণ", "ত", "ন্ত্র"], minLevel: 3 },
          { word: "অধিকার", parts: ["অ", "ধি", "কা", "র"], minLevel: 3 },
          { word: "কর্তব্য", parts: ["ক", "র্ত", "ব্য"], minLevel: 3 },
          { word: "দায়িত্ব", parts: ["দা", "য়ি", "ত্ব"], minLevel: 3 },
          { word: "আন্তর্জাতিক", parts: ["আ", "ন্ত", "র্জা", "তি", "ক"], minLevel: 3 },
          { word: "রাষ্ট্রদূত", parts: ["রা", "ষ্ট্র", "দূ", "ত"], minLevel: 3 },
          { word: "প্রধানমন্ত্রী", parts: ["প্র", "ধা", "ন", "ম", "ন্ত্রী"], minLevel: 3 },
          { word: "রাষ্ট্রপতি", parts: ["রা", "ষ্ট্র", "প", "তি"], minLevel: 3 },
          { word: "মন্ত্রিসভা", parts: ["ম", "ন্ত্রি", "স", "ভা"], minLevel: 3 },
          { word: "সংস্কৃতি", parts: ["সং", "স্কৃ", "তি"], minLevel: 3 },
          { word: "ঐতিহ্য", parts: ["ঐ", "তি", "হ্য"], minLevel: 3 },
          { word: "সাহিত্য", parts: ["সা", "হি", "ত্য"], minLevel: 3 },
          { word: "শিল্পকলা", parts: ["শি", "ল্প", "ক", "লা"], minLevel: 3 },
          { word: "জাদুঘর", parts: ["জা", "দু", "ঘ", "র"], minLevel: 3 },
          { word: "চিড়িয়াখানা", parts: ["চি", "ড়ি", "য়া", "খা", "না"], minLevel: 3 },
          { word: "বিমানবন্দর", parts: ["বি", "মা", "ন", "ব", "ন্দ", "র"], minLevel: 3 },
          { word: "বিশ্ববিদ্যালয়", parts: ["বি", "শ্ব", "বি", "দ্যা", "ল", "য়"], minLevel: 3 },
          { word: "চিকিৎসা", parts: ["চি", "কি", "ৎ", "সা"], minLevel: 3 },
          { word: "অস্ত্রোপচার", parts: ["অ", "স্ত্রো", "প", "চা", "র"], minLevel: 3 },
          { word: "পরীক্ষাগার", parts: ["প", "রী", "ক্ষা", "গা", "র"], minLevel: 3 },
          { word: "রাসায়নিক", parts: ["রা", "সা", "য়", "নি", "ক"], minLevel: 3 },
          { word: "পদার্থ", parts: ["প", "দা", "র্থ"], minLevel: 3 },
          { word: "উদ্ভিদ", parts: ["উ", "দ্ভি", "দ"], minLevel: 3 },
          { word: "প্রাণী", parts: ["প্রা", "ণী"], minLevel: 3 },
          { word: "পরিবেশদূষণ", parts: ["প", "রি", "বে", "শ", "দূ", "ষ", "ণ"], minLevel: 3 },
          { word: "জলবায়ু", parts: ["জ", "ল", "বা", "য়ু"], minLevel: 3 },
          { word: "ভূমিকম্প", parts: ["ভূ", "মি", "ক", "ম্প"], minLevel: 3 },
          { word: "ঘূর্ণিঝড়", parts: ["ঘূ", "র্ণি", "ঝ", "ড়"], minLevel: 3 },
          { word: "বন্যা", parts: ["ব", "ন্যা"], minLevel: 3 },
          { word: "আগ্নেয়গিরি", parts: ["আ", "গ্নে", "য়", "গি", "রি"], minLevel: 3 },
          { word: "মহাকাশ", parts: ["ম", "হা", "কা", "শ"], minLevel: 3 },
          { word: "উপগ্রহ", parts: ["উ", "প", "গ্র", "হ"], minLevel: 3 },
          { word: "নক্ষত্র", parts: ["ন", "ক্ষ", "ত্র"], minLevel: 3 },
          { word: "দূরবীক্ষণ", parts: ["দূ", "র", "বী", "ক্ষ", "ণ"], minLevel: 3 },
          { word: "অণুবীক্ষণ", parts: ["অ", "ণু", "বী", "ক্ষ", "ণ"], minLevel: 3 },
          { word: "পেশাজীবী", parts: ["পে", "শা", "জী", "বী"], minLevel: 3 },
          { word: "ব্যবসায়ী", parts: ["ব্য", "ব", "সা", "য়ী"], minLevel: 3 },
          { word: "বিনিয়োগ", parts: ["বি", "নি", "য়ো", "গ"], minLevel: 3 },
          { word: "বিজ্ঞাপন", parts: ["বি", "জ্ঞা", "প", "ন"], minLevel: 3 },
          { word: "পর্যটন", parts: ["প", "র্য", "ট", "ন"], minLevel: 3 },
          { word: "বিনোদন", parts: ["বি", "নো", "দ", "ন"], minLevel: 3 },
          { word: "কলকারখানা", parts: ["ক", "ল", "কা", "র", "খা", "না"], minLevel: 3 },
          { word: "যানবাহন", parts: ["যা", "ন", "বা", "হ", "ন"], minLevel: 3 },
          { word: "যোগাযোগ", parts: ["যো", "গা", "যো", "গ"], minLevel: 3 },
          { word: "তথ্যপ্রযুক্তি", parts: ["ত", "থ্য", "প্র", "যু", "ক্তি"], minLevel: 3 },
          { word: "আবহাওয়া", parts: ["আ", "ব", "হা", "ও", "য়া"], minLevel: 3 },
          { word: "প্রয়োজনীয়", parts: ["প্র", "য়ো", "জ", "নী", "য়"], minLevel: 3 },
          { word: "গুরুত্বপূর্ণ", parts: ["গু", "রু", "ত্ব", "পূ", "র্ণ"], minLevel: 3 },
          { word: "অসাধারণ", parts: ["অ", "সা", "ধা", "র", "ণ"], minLevel: 3 },
          { word: "বুদ্ধিমান", parts: ["বু", "দ্ধি", "মা", "ন"], minLevel: 3 },
          { word: "পরিশ্রমী", parts: ["প", "রি", "শ্র", "মী"], minLevel: 3 },
          { word: "অনুসন্ধান", parts: ["অ", "নু", "স", "ন্ধা", "ন"], minLevel: 3 },
          { word: "পর্যবেক্ষণ", parts: ["প", "র্য", "বে", "ক্ষ", "ণ"], minLevel: 3 },
          { word: "সমালোচনা", parts: ["স", "মা", "লো", "চ", "না"], minLevel: 3 },
          { word: "প্রতিযোগিতা", parts: ["প্র", "তি", "যো", "গি", "তা"], minLevel: 3 },
          { word: "পুরস্কার", parts: ["পু", "র", "স্কা", "র"], minLevel: 3 },
          { word: "সম্মাননা", parts: ["স", "ম্মা", "ন", "না"], minLevel: 3 },
          { word: "অভিজ্ঞতা", parts: ["অ", "ভি", "জ্ঞ", "তা"], minLevel: 3 },
          { word: "স্মরণীয়", parts: ["স্ম", "র", "ণী", "য়"], minLevel: 3 },
          { word: "ভ্রমণকাহিনী", parts: ["ভ্র", "ম", "ণ", "কা", "হি", "নী"], minLevel: 3 },
          { word: "জীবনী", parts: ["জী", "ব", "নী"], minLevel: 3 },
          { word: "আত্মজীবনী", parts: ["আ", "ত্ম", "জী", "ব", "নী"], minLevel: 3 },
          { word: "নারায়ণগঞ্জ", parts: ["না", "রা", "য়", "ণ", "গ", "ঞ্জ"], minLevel: 3 },
          { word: "চট্টগ্রাম", parts: ["চ", "ট্ট", "গ্রা", "ম"], minLevel: 3 },
          { word: "রাজশাহী", parts: ["রা", "জ", "শা", "হী"], minLevel: 3 },
          { word: "কলকাতা", parts: ["কো", "ল", "কা", "তা"], minLevel: 3 },
          { word: "হিমালয়", parts: ["হি", "মা", "ল", "য়"], minLevel: 3 },
          { word: "সুন্দরবন", parts: ["সু", "ন্দ", "র", "ব", "ন"], minLevel: 3 },
          { word: "পদ্মানদী", parts: ["প", "দ্মা", "ন", "দী"], minLevel: 3 },
          { word: "ব্রহ্মপুত্র", parts: ["ব্র", "হ্ম", "পু", "ত্র"], minLevel: 3 },
          { word: "বৃহস্পতিবার", parts: ["বৃ", "হ", "স্প", "তি", "বা", "র"], minLevel: 3 },
          { word: "শুক্রবার", parts: ["শু", "ক্র", "বা", "র"], minLevel: 3 },
          { word: "জানুয়ারি", parts: ["জা", "নু", "য়া", "রি"], minLevel: 3 },
          { word: "ফেব্রুয়ারি", parts: ["ফে", "ব্রু", "য়া", "রি"], minLevel: 3 },
          { word: "ডিসেম্বর", parts: ["ডি", "সে", "ম্ব", "র"], minLevel: 3 },
          { word: "জন্মগ্রহণ", parts: ["জ", "ন্ম", "গ্র", "হ", "ণ"], minLevel: 3 },
          { word: "মৃত্যুবরণ", parts: ["মৃ", "ত্যু", "ব", "র", "ণ"], minLevel: 3 },
          { word: "প্রকাশিত", parts: ["প্র", "কা", "শি", "ত"], minLevel: 3 },
          { word: "সম্পাদিত", parts: ["স", "ম্পা", "দি", "ত"], minLevel: 3 },
          { word: "অনুদিত", parts: ["অ", "নু", "দি", "ত"], minLevel: 3 },
          { word: "গ্রহণযোগ্য", parts: ["গ্র", "হ", "ণ", "যো", "গ্য"], minLevel: 3 },
          { word: "অবিশ্বাস্য", parts: ["অ", "বি", "শ্বা", "স্য"], minLevel: 3 },
          { word: "অনুপ্রেরণা", parts: ["অ", "নু", "প্রে", "র", "ণা"], minLevel: 3 },
          { word: "পরিচয়পত্র", parts: ["প", "রি", "চ", "য়", "প", "ত্র"], minLevel: 3 },
          { word: "আমন্ত্রণ", parts: ["আ", "ম", "ন্ত্র", "ণ"], minLevel: 3 },
          { word: "উপহার", parts: ["উ", "প", "হা", "র"], minLevel: 3 },
          { word: "অভিনন্দন", parts: ["অ", "ভি", "ন", "ন্দ", "ন"], minLevel: 3 },
          { word: "সহানুভূতি", parts: ["স", "হা", "নু", "ভূ", "তি"], minLevel: 3 },
          { word: "কৃতজ্ঞতা", parts: ["কৃ", "ত", "জ্ঞ", "তা"], minLevel: 3 },
          { word: "প্রতিশ্রুতি", parts: ["প্র", "তি", "শ্রু", "তি"], minLevel: 3 },
          { word: "সমর্থন", parts: ["স", "ম", "র্থ", "ন"], minLevel: 3 },
          { word: "বিরোধিতা", parts: ["বি", "রো", "ধি", "তা"], minLevel: 3 },
          { word: "আলো ঝলমলে", parts: ["আ", "লো", "ঝ", "ল", "ম", "লে"], minLevel: 3 },
          { word: "বাস্তবায়ন", parts: ["বা", "স্ত", "বা", "য়", "ন"], minLevel: 3 },
          { word: "শক্তিশালী", parts: ["শ", "ক্তি", "শা", "লী"], minLevel: 3 },
          { word: "স্বাস্থ্যবান", parts: ["স্বা", "স্থ্য", "বা", "ন"], minLevel: 3 },
          { word: "আগামীকাল", parts: ["আ", "গা", "মী", "কা", "ল"], minLevel: 3 },
          { word: "সপ্তাহান্ত", parts: ["স", "প্তাহা", "ন্ত"], minLevel: 3 },
          { word: "বিশ্বাসঘাতক", parts: ["বি", "শ্বা", "স", "ঘা", "ত", "ক"], minLevel: 3 },
          { word: "প্রতিহিংসা", parts: ["প্র", "তি", "হিং", "সা"], minLevel: 3 },
          { word: "সহযোগিতা", parts: ["স", "হ", "যো", "গি", "তা"], minLevel: 3 },
          { word: "প্রতিদ্বন্দ্বী", parts: ["প্র", "তি", "দ্ব", "ন্দ্বী"], minLevel: 3 },
          { word: "আন্দোলন", parts: ["আ", "ন্দো", "ল", "ন"], minLevel: 3 },
          { word: "বিপ্লব", parts: ["বি", "প্ল", "ব"], minLevel: 3 },
          { word: "সংস্কার", parts: ["সং", "স্কা", "র"], minLevel: 3 },
          { word: "উদ্বোধন", parts: ["উ", "দ্বো", "ধ", "ন"], minLevel: 3 },
          { word: "সমাপ্তি", parts: ["স", "মা", "প্তি"], minLevel: 3 },
          { word: "উদ্দেশ্য", parts: ["উ", "ദ്ദേ", "শ্য"], minLevel: 3 },
          { word: "লক্ষ্য", parts: ["ল", "ক্ষ্য"], minLevel: 3 },
          { word: "সম্ভাবনা", parts: ["স", "ম্ভা", "ব", "না"], minLevel: 3 },
          { word: "নিরাপত্তা", parts: ["নি", "রা", "প", "ত্তা"], minLevel: 3 },
          { word: "দুর্ঘটনা", parts: ["দু", "র্ঘ", "ট", "না"], minLevel: 3 },
          { word: "সিদ্ধান্ত", parts: ["সি", "দ্ধা", "ন্ত"], minLevel: 3 },
          { word: "খ্যাতি", parts: ["খ্যা", "তি"], minLevel: 3 },
          { word: "দুর্নাম", parts: ["দু", "র্না", "ম"], minLevel: 3 },
          { word: "সম্মান", parts: ["স", "ম্মা", "ন"], minLevel: 3 },
          { word: "অপমান", parts: ["অ", "প", "মা", "ন"], minLevel: 3 },
          { word: "প্রশংসা", parts: ["প্র", "শং", "সা"], minLevel: 3 },
          { word: "অনুগ্রহ", parts: ["অ", "নু", "গ্র", "হ"], minLevel: 3 },
          { word: "আশীর্বাদ", parts: ["আ", "শী", "র্বা", "দ"], minLevel: 3 },
          { word: "অভিশাপ", parts: ["অ", "ভি", "শা", "প"], minLevel: 3 },
          { word: "নিয়ন্ত্রণ", parts: ["নি", "য়", "ন্ত্র", "ণ"], minLevel: 3 },
          { word: "নির্ভরশীলতা", parts: ["নি", "র্ভ", "র", "শী", "ল", "তা"], minLevel: 3 },
          { word: "পার্থক্য", parts: ["পা", "র্থ", "ক্য"], minLevel: 3 },
          { word: "সাদৃশ্য", parts: ["সা", "দৃ", "শ্য"], minLevel: 3 },
          { word: "বৈসাদৃশ্য", parts: ["বৈ", "সা", "দৃ", "শ্য"], minLevel: 3 },
          { word: "অনুপস্থিত", parts: ["অ", "নু", "প", "স্থি", "ত"], minLevel: 3 },
          { word: "উপস্থিত", parts: ["উ", "প", "স্থি", "ত"], minLevel: 3 },
          { word: "প্রস্থান", parts: ["প্র", "স্থা", "ন"], minLevel: 3 },
          { word: "অভ্যর্থনা", parts: ["অ", "ভ্য", "র্থ", "না"], minLevel: 3 },
          { word: "আতিথেয়তা", parts: ["আ", "তি", "থে", "য়", "তা"], minLevel: 3 },
          { word: "নিমন্ত্রণ", parts: ["নি", "ম", "ন্ত্র", "ণ"], minLevel: 3 },
          { word: "আবিষ্কার", parts: ["আ", "বি", "ষ্কা", "র"], minLevel: 3 },
          { word: "অনুশীলন", parts: ["অ", "নু", "শী", "ল", "ন"], minLevel: 3 },
          { word: "প্রস্তুতি", parts: ["প্র", "স্তু", "তি"], minLevel: 3 },
          { word: "আয়োজন", parts: ["আ", "য়ো", "জ", "ন"], minLevel: 3 },
          { word: "উদ্যোগ", parts: ["উ", "দ্যো", "গ"], minLevel: 3 },
          { word: "অংশগ্রহণ", parts: ["অং", "শ", "গ্র", "হ", "ণ"], minLevel: 3 },
          { word: "সমবেদনা", parts: ["স", "ম", "বে", "দ", "না"], minLevel: 3 },
          { word: "অধ্যাপক", parts: ["অ", "ধ্যা", "প", "ক"], minLevel: 3 },
          { word: "অধ্যক্ষ", parts: ["অ", "ধ্য", "ক্ষ"], minLevel: 3 },
          { word: "রেজিস্ট্রার", parts: ["রে", "জি", "স্ট্রা", "র"], minLevel: 3 },
          { word: "গ্রন্থাগার", parts: ["গ্র", "ন্থা", "গা", "র"], minLevel: 3 },
          { word: "গ্রন্থাগারিক", parts: ["গ্র", "ন্থা", "গা", "রি", "ক"], minLevel: 3 },
          { word: "প্রকাশনা", parts: ["প্র", "কা", "শ", "না"], minLevel: 3 },
          { word: "মুদ্রণ", parts: ["মু", "দ্র", "ণ"], minLevel: 3 },
          { word: "পরিবেশক", parts: ["প", "রি", "বে", "শ", "ক"], minLevel: 3 },
          { word: "ক্রেডিট কার্ড", parts: ["ক্রে", "ডি", "ট", "কা", "র্ড"], minLevel: 3 },
          { word: "ডেবিট কার্ড", parts: ["ডে", "বি", "ট", "কা", "র্ড"], minLevel: 3 },
          { word: "অর্থনীতিবিদ", parts: ["অ", "র্থ", "নী", "তি", "বি", "দ"], minLevel: 3 },
          { word: "বিজ্ঞানী", parts: ["বি", "জ্ঞা", "নী"], minLevel: 3 },
          { word: "গবেষক", parts: ["গ", "বে", "ষ", "ক"], minLevel: 3 },
          { word: "মনোবিজ্ঞানী", parts: ["ম", "নো", "বি", "জ্ঞা", "নী"], minLevel: 3 },
          { word: "সমাজবিজ্ঞানী", parts: ["স", "মা", "জ", "বি", "জ্ঞা", "নী"], minLevel: 3 },
          { word: "নৃতত্ত্ববিদ", parts: ["নৃ", "ত", "ত্ত্ব", "বি", "দ"], minLevel: 3 },
          { word: "প্রত্নতত্ত্ববিদ", parts: ["প্র", "ত্ন", "ত", "ত্ত্ব", "বি", "দ"], minLevel: 3 },
          { word: "জ্যোতির্বিদ", parts: ["জ্যো", "তি", "র্বি", "দ"], minLevel: 3 },
          { word: "চিকিৎসক", parts: ["চি", "কি", "ৎস", "ক"], minLevel: 3 },
          { word: "ফার্মাসিস্ট", parts: ["ফা", "র্মা", "সি", "স্ট"], minLevel: 3 },
          { word: "মহাকাশচারী", parts: ["ম", "হা", "কা", "শ", "চা", "রী"], minLevel: 3 },
          { word: "বৈমানিক", parts: ["বৈ", "মা", "নি", "ক"], minLevel: 3 },
          { word: "পর্বতারোহী", parts: ["প", "র্ব", "তা", "রো", "হী"], minLevel: 3 },
          { word: "অগ্নি নির্বাপক", parts: ["অ", "গ্নি", "নি", "র্বা", "প", "ক"], minLevel: 3 },
          { word: "নিরাপত্তারক্ষী", parts: ["নি", "রা", "প", "ত্তা", "র", "ক্ষী"], minLevel: 3 },
          { word: "পরিচ্ছনতাকর্মী", parts: ["প", "রি", "চ্ছ", "ন্ন", "তা", "ক", "র্মী"], minLevel: 3 },
          { word: "গৃহকর্মী", parts: ["গৃ", "হ", "ক", "র্মী"], minLevel: 3 },
          { word: "রাজনীতিবিদ", parts: ["রা", "জ", "নী", "তি", "বি", "দ"], minLevel: 3 },
          { word: "কূটনীতিবিদ", parts: ["কূ", "ট", "নী", "তি", "বি", "দ"], minLevel: 3 },
          { word: "অভিনেতা", parts: ["অ", "ভি", "নে", "তা"], minLevel: 3 },
          { word: "অভিনেত্রী", parts: ["অ", "ভি", "নে", "ত্রী"], minLevel: 3 },
          { word: "নৃত্যশিল্পী", parts: ["নৃ", "ত্য", "শি", "ল্পী"], minLevel: 3 },
          { word: "সুরকার", parts: ["সু", "র", "কা", "র"], minLevel: 3 },
          { word: "গীতিকার", parts: ["গী", "তি", "কা", "র"], minLevel: 3 },
          { word: "চিত্রকর", parts: ["চি", "ত্র", "ক", "র"], minLevel: 3 },
          { word: "ভাস্কর", parts: ["ভা", "স্ক", "র"], minLevel: 3 },
          { word: "আলোকচিত্রী", parts: ["আ", "লো", "ক", "চি", "ত্রী"], minLevel: 3 },
          { word: "চলচ্চিত্রকার", parts: ["চ", "ল", "চ্চি", "ত্র", "কা", "র"], minLevel: 3 },
          { word: "খেলোয়াড়", parts: ["খে", "লো", "য়া", "ড়"], minLevel: 3 },
          { word: "উদ্যোক্তা", parts: ["উ", "দ্যো", "ক্তা"], minLevel: 3 },
          { word: "হিসাবরক্ষক", parts: ["হি", "সা", "ব", "র", "ক্ষ", "ক"], minLevel: 3 },
          { word: "বাজার বিশ্লেষক", parts: ["বা", "জা", "র", "বি", "শ্লে", "ষ", "ক"], minLevel: 3 },
          { word: "মানব সম্পদ", parts: ["মা", "ন", "ব", "স", "ম্প", "দ"], minLevel: 3 },
          { word: "জনসংযোগ", parts: ["জ", "ন", "সং", "যো", "গ"], minLevel: 3 },
          { word: "অনুচ্ছেদ", parts: ["অ", "নু", "চ্ছে", "দ"], minLevel: 3 },
          { word: "শিরোনাম", parts: ["শি", "রো", "না", "ম"], minLevel: 3 },
          { word: "সূচিপত্র", parts: ["সূ", "চি", "প", "ত্র"], minLevel: 3 },
          { word: "ভূমিকা", parts: ["ভূ", "মি", "কা"], minLevel: 3 },
          { word: "উপসংহার", parts: ["উ", "প", "সং", "হা", "র"], minLevel: 3 },
          { word: "পরিশিষ্ট", parts: ["প", "রি", "শি", "ষ্ট"], minLevel: 3 },
          { word: "গ্রন্থপঞ্জি", parts: ["গ্র", "ন্থ", "প", "ঞ্জি"], minLevel: 3 },
          { word: "পাদটীকা", parts: ["পা", "দ", "টী", "কা"], minLevel: 3 },
          { word: "ছদ্মনাম", parts: ["ছ", "দ্ম", "না", "ম"], minLevel: 3 },
          { word: "চিত্রনাট্য", parts: ["চি", "ত্র", "না", "ট্য"], minLevel: 3 },
          { word: "সংলাপ", parts: ["সং", "লা", "প"], minLevel: 3 },
          { word: "নির্দেশনা", parts: ["নি", "র্দে", "শ", "না"], minLevel: 3 },
          { word: "প্রযোজনা", parts: ["প্র", "যো", "জ", "না"], minLevel: 3 },
          { word: "আবহ সঙ্গীত", parts: ["আ", "ব", "হ", "সং", "গী", "ত"], minLevel: 3 },
          { word: "শব্দ গ্রহণ", parts: ["শ", "ব্দ", "গ্র", "হ", "ণ"], minLevel: 3 },
          { word: "চলচ্চিত্র গ্রহণ", parts: ["চ", "ল", "চ্চি", "ত্র", "গ্র", "হ", "ণ"], minLevel: 3 },
          { word: "বিশেষ প্রভাব", parts: ["বি", "শে", "ষ", "প্র", "ভা", "ব"], minLevel: 3 },
          { word: "অ্যানিমেশন", parts: ["অ্যা", "নি", "মে", "শ", "ন"], minLevel: 3 },
          { word: "বার্ষিক", parts: ["বা", "র্ষি", "ক"], minLevel: 3 },
          { word: "সাপ্তাহিক", parts: ["সা", "প্তা", "হি", "ক"], minLevel: 3 },
          { word: "দৈনিক", parts: ["দৈ", "নি", "ক"], minLevel: 3 },
          { word: "সংরক্ষণ", parts: ["সং", "র", "ক্ষ", "ণ"], minLevel: 3 },
          { word: "দূষণ", parts: ["দূ", "ষ", "ণ"], minLevel: 3 },
        ];